### PR TITLE
Cleanup README

### PR DESCRIPTION
**Pull request by ryanmjacobs**
* Fix some grammar
* Markdown formatting so it looks nice on GitHub :D

(If you want to double-check my work, view https://github.com/ryanmjacobs/esp-open-sdk/blob/rename-readme/README.md)

### CODE REVIEW

**Comment by pfalcon** [comment]
It's nice that it looks good on github, but does it look good in developer's console, i.e. are all lines 70-something chars, etc.?

**Comment by ryanmjacobs** [comment]
@pfalcon If I change it to a "hard" 80 will that work? Or does it have to be a "hard" 70?

**Comment by pfalcon** [comment]
Yes, I'd appreciate that. 80 is too much, 77 is hard max, 75 is soft max, and 70 is good enough.

**Comment by ryanmjacobs** [comment]
Okay, I think that should be good.

**Comment by pfalcon** [comment]
Squashed together and merged. Thanks!

**Pull request closed without merging**
