### PR TITLE
SDK Update and Bugfix

### PR DESCRIPTION
**Pull request by tobiaskohlbau**
Adds SDK 1.5.4 from 20.06.2016 and solves compiling issue for GCC 6.1.

Have a look at:
https://github.com/jcmvbkbc/crosstool-NG/issues/24

af1a969ded2de22685a9f0aefe231f92a1f0556e should be reverted if bug is fixed upstream.

### CODE REVIEW

**Comment by dpgeorge** [comment]
The issue with compiling with gcc 6.1 was fixed upstream.

**Comment by tobiaskohlbau** [comment]
I've noticed it already, thanks for reminding.

Patch is reverted and submodule updated.

**Comment by pfalcon** [comment]
Update to crosstool-NG pushed with a compliant commit message as https://github.com/pfalcon/esp-open-sdk/commit/6cc801e9c32a452807545dcbfe61647b68efb228.

**Comment by jeremyd2019** [comment]
re 96707e8 - I think that's wrong.  I got an error when I applied that commit, whereas it builds successfully with sdk 1.5.3 without that commit.

**Comment by pfalcon** [comment]
Update to 1.5.4 cherry-picked. 1.5.4 was made a default.

**Comment by br101** [comment]
Sorry, but 1.5.2. is still default (VENDOR_SDK = 1.5.2)

**Comment by pfalcon** [comment]
D'oh! Thanks, fixed.

**Pull request closed without merging**
