### PR TITLE
Add support for SDK 0.9.5 final + patch1 + C99

### PR DESCRIPTION
**Pull request by sej7278**
Accidentally closed PR #20 so added C99 patch to this to replace it.

N.B. existing C99 patch for 094 used, patch figures out the 1 line offset.

### CODE REVIEW

**Comment by pfalcon** [comment]
The list of 0.9.5 changes (http://bbs.espressif.com/viewtopic.php?f=5&t=154) looks good, but this point concerns me:

> 6、update to boot v1.2 to support new format user.bin；

What's that "new format", are there any more info/docs? Can you confirm that projects built with current gcc/esptool.py flash and run ok?

**Comment by pfalcon** [comment]
So, merged, thanks, but I'd appreciate answers to questions above.

Actually, is there IoT_Demo release corresponding to this sdk version? (yeah, sorry, don't have enough time now to wade thru esp8266.com forum...)

**Comment by sej7278** [comment]
boot stuff seems to be covered in readme.txt, its disabled by default anyway, but seems to add some options around SPI:

```
1 compile options

(1) COMPILE
    Possible value: gcc
    Default value: 
    If not set, use xt-xcc by default.

(2) BOOT
    Possible value: none/old/new
      none: no need boot
      old: use boot_v1.1
      new: use boot_v1.2
    Default value: none

(3) APP
    Possible value: 0/1/2
      0: original mode, generate eagle.app.v6.flash.bin and eagle.app.v6.irom0text.bin
      1: generate user1
      2: generate user2
    Default value: 0

(3) SPI_SPEED
    Possible value: 20/26.7/40/80
    Default value: 40

(4) SPI_MODE
    Possible value: QIO/QOUT/DIO/DOUT
    Default value: QIO

(5) SPI_SIZE
    Possible value: 256/512/1024/2048/4096
    Default value: 512

For example:
    make COMPILE=gcc BOOT=new APP=1 SPI_SPEED=40 SPI_MODE=QIO SPI_SIZE=512

2 You can also use gen_misc to make and generate specific bin you needed.
    Linux: ./gen_misc.sh
    Windows: gen_misc.bat
    Follow the tips and steps.
```

**Comment by pfalcon** [comment]
Thanks for hint about readme. So, it looks like those "bootloaders" are related to cloud-update builds, though they may contain info useful outside that. I also see that IoT example is included in tarball, so clarifying, I was asking about "complete" example which included source for components like espconn and lwip, which was available for one (some?) of older releases (separately).

**Pull request closed without merging**
