### PR TITLE
Added RAM optimization fix (see: http://bbs.espressif.com/viewtopic…

### PR DESCRIPTION
**Pull request by slaff**
….php?f=5&t=734)

### CODE REVIEW

**Comment by pfalcon** [comment]
See #67.

**Comment by slaff** [comment]
@pfalcon Is just the commit message an issue or you do not like the patch? If it is the message I tried to reword it a bit.

**Comment by pfalcon** [comment]
Yes, commit the message is the problem, and yes, it needs rewording. For reference, what "SDRAM" is: https://en.wikipedia.org/wiki/SDRAM

**Comment by slaff** [comment]
@pfalcon  Is this better: "Patch freeing some memory for the apps" , "https://github.com/slaff/esp-open-sdk/commit/f3b6200206a8a4ec3677f8e0896286ea5090e715" ?

**Comment by pfalcon** [comment]
Replacing "SDRAM" with just "RAM" is good enough.

**Comment by pfalcon** [comment]
If you push new version of a patch, please tell about that - github doesn't notify about such things automatically.

**Comment by eriksl** [comment]
It the esp8266 context, it's important what ram is meant. Is it iram, where the .text code ends up, and which we can use very very much, every byte of it, or is it dram (data), which at least I don't need that much of.

**Comment by slaff** [comment]
@pfalcon I pushed a week ago a reworded commit and you can see it here (https://github.com/pfalcon/esp-open-sdk/pull/68/commits). If you want better commit message just cherry pick this commit, reword it and add it to your master branch.

**Comment by slaff** [comment]
Hi Paul,
  I pushed a week ago a reworded commit and you can see it here (
https://github.com/pfalcon/esp-open-sdk/pull/68/commits). If you want
better commit message just cherry pick this commit, reword it and add it to
your master branch.

Regards,
 Slavey

**Comment by pfalcon** [comment]
Merged, thanks.

**Pull request closed without merging**
