### PR TITLE
Add support for SDK 0.9.5 beta 1

### PR DESCRIPTION
**Pull request by sej7278**
Not selected by default, just uncomment #VENDOR_SDK = 0.9.5b1

Been using this with nodemcu 0.9.5 for over a week with no issues.

### CODE REVIEW

**Comment by sej7278** [comment]
does anyone have any comment on this? its only an option, not the default so it can't really harm to merge it.

it doesn't look like espressif are doing much non-rtos development at the moment so i wonder if it'll ever come out of beta.

**Comment by pfalcon** [comment]
Thanks. My plan is to stay on top of this stuff, which means I'd prefer to read about 0.9.5 first before merging it, which in turn takes some time. I'll surely merge this on weekend.

**Comment by sej7278** [comment]
ah actually maybe hold it off for a bit - apparently 0.9.5 final (or at least a newer beta) is due next week.

**Comment by pfalcon** [comment]
Thanks, merged. When 0.9.5 final released, we then can upgrade easily.

**Pull request merged**
