### PR TITLE
Added SDK 1.1.0 patch 1. 

### PR DESCRIPTION
**Pull request by slaff**
See: http://bbs.espressif.com/viewtopic.php?f=5&t=508.

### CODE REVIEW

**Comment by pfalcon** [comment]
Have you tested this? Likely not, because your change violates make syntax.

**Comment by slaff** [comment]
Surprisingly it worked on my vagrant ubuntu box. But I saw that the indentation is not correct so I can try to change it with some decent text editor.

**Comment by pfalcon** [comment]
Please change, classical make requires tab chars as indent. I don't know if they gave up on that in the very latest version, but a lot of people still runs classical make.

**Comment by slaff** [comment]
It should work now. I somehow committed older version of the Makefile :(. Thanks for pointing this out.

**Comment by slaff** [comment]
@pfalcon Can you check if the changed Makefile works on your system?

**Comment by pfalcon** [comment]
Everything, ok, thanks, merged! (Just please consider squashing such changes in the future.)

**Comment by slaff** [comment]
@pfalcon Thanks! 
> Just please consider squashing such changes in the future.

Understood.

**Pull request closed without merging**
