### PR TITLE
Add new header esp_protos.h to all SDKs

### PR DESCRIPTION
**Pull request by olaf-mandel**
Note: this is only one commit, but it depends on the pending PR #119: so github shows 28 commits here.

Several functions used by the public interface of the SDK are not properly declared in the headers. So these are implicitly declared on first use and no checking on the call parameters (number and type) or return value type is done.
    
Other projects have a espmissingincludes.h header that (among others) lists these prototypes. But there are many different versions in different projects and there seems to be no central source where to send patches etc. So adding a similar file here as the central source for it seems appropriate.
    
The file is not based of off the various espmissingincludes.h, though it was compared to those. The file is based on the output of an automated script that parses the ld/eagle.rom.addr.v6.ld and all lib/*.a files to get a list of functions and then compares against the headers in include to find used functions without a propper declaration. The prototypes given are either taken from the SDK API Guide, adapted from the standard libc equivalent or guessed...

Question: should I place the script that generated the esp_protos.h file in the project so it is available if e.g. a new SDK version comes out?

### CODE REVIEW

**Comment by pfalcon** [comment]
> Note: this is only one commit, but it depends on the pending PR #119: so github shows 28 commits here.

Ok, so please don't do it. Don't depend on unmerged patches, depend only current master HEAD (and be ready to rebase changes, to depend exactly on *current* master HEAD). I've hinted that doing massive changes are bad yet at https://github.com/pfalcon/esp-open-sdk/pull/117#issuecomment-168333420 , and now we expectedly see effect of that (because the effects show every single time when someone breaks the golden rule of "avoid making massive changes"). The expected workflow for contributing to opensource projects is: 0. Don't make massive changes. 1. Make a small change, submit, wait for feedback. 2. If a change is merged, continue, but still don't make massive changes. 3. If a changes is not merged, either argue your case, get arguments of the maintainers why it doesn't fit, or reconsider your strategy. 4. If you need to make massive changes, discuss them first with the maintainers.

**Comment by pfalcon** [comment]
Now, about the idea of this change: I'm positive about it (actually, that's what I wanted to ask: Why "cleanup"? There're lot of *real* things to do and issues to resolve instead).

But: it all should be well thought out and structured. Let me share what I have in mind in the next comment (may take some time to appear).

**Comment by pfalcon** [comment]
Ok, so suppose you want to provide open access to all SDK functions (and that should be the aim), how to do that? Having a single massive header obviously won't do (it's not maintainable). And SDK actually has its natural structure - it consists of number of libs, each having number of object files inside. Then, it's pretty natural to have a header per such object, all organized in hierarchy.

E.g., there would be pp/esf_buf.h and main/ets_timer_arm_new.h. ("main" is not ideal, but everyone knows that esp8266 software/docs are not ideal, at least it directly an unambiguously maps to specific SDK component). In this picture, the bootrom is just another component, akin to a library containing single object file. The only thing to decide how to name it, and perhaps bootrom/bootrom.h can be shortened to just esp_rom.h .

So, how to organize this? This can be a separate project, eventually added as a submodule to esp-open-sdk.

**Comment by olaf-mandel** [comment]
> Ok, so suppose you want to provide open access to all SDK functions (and that should be the aim), [...]

Actually, I was scratching a different itch: compiler warnings about implicitly undeclared functions. This is what others addressed with `espmissingincludes.h` files. So I am not trying (at this point) to declare all ROM & SDK functions but only those that are used by the SDK headers. I agree that declaring more functions is a logical expansion of this.

As for organization: at least at the current stage (silence compiler warnings) I think the single file is still acceptable. But your suggestion to split things up by library has a lot of merit as well: this *is* how most library interfaces work (never more than one lib per header). Another option would be patching the actual SDK headers: e.g. below the section of `osapi.h` that contains:

    #define os_memcmp ets_memcmp
    #define os_memcpy ets_memcpy
    /* ... */

One could add the matching declarations:

    int ets_memcmp(const void *lhs, const void *rhs, size_t count);
    void *ets_memcpy(void *dest, const void *src, size_t count);
    /* ... */

Advantage: the SDK headers get "fixed" (i.e. self-contained, no longer necessary for the user to include another header). Disadvantage: I think writing a script that generates the proper patches will be difficult because of finding the proper place to add the declarations. So this would become a manual job: not so nice...

**Comment by olaf-mandel** [comment]
> [...] what I wanted to ask: Why "cleanup"? There're lot of real things to do and issues to resolve instead

Why cleanup: when I started looking into esp-open-sdk, I tried finding out what it does and I found the Makefile difficult to follow. So I wanted to bring it into a shape that I considered easier to understand.

As for other issues: which did you have in mind? I am currently working on some examples (but I am slow there as I am also learning about ESP at the same time). And I still am not happy about not fingerprinting the downloads (bitbake uses fingerprints in all its recipes to ensure download integrity).

**Comment by pfalcon** [comment]
> at least at the current stage (silence compiler warnings) I think the single file is still acceptable.

Kinda yes, but it will turn out to be wasted work when someone will come up with a project for complete headers, while it could be start of such project. That said, if you don't feel like starting such project, adding just a single file is ok. The name is probably ok too. Location is to be discussed in #119 review.

**Comment by pfalcon** [comment]
Answering other questions: 

I don't think that we should patch standard headers. Well, at least not with inline prototypes. Perhaps we can patch "#include "esp_protos.h"" in.

I don't think that adding adhoc scripts to this repo is good idea (and I don't think that once first version of a header is made, many folks will want to rerun such script vs doing small rare manual adjustments. I suggest you creating your own repos for such tools, like other folks have: https://github.com/pfalcon/esp-sdk-tools , https://bitbucket.org/foogod/esp8266-re-tools (if you didn't hear about foogod's xtobjdis, mind also https://github.com/pfalcon/ScratchABit).

**Comment by pfalcon** [comment]
> As for other issues: which did you have in mind?

https://github.com/pfalcon/esp-open-sdk/pull/110 , https://github.com/pfalcon/esp-open-sdk/issues/118

> I am currently working on some examples

Examples are good, yes - I failed to find ones with clear licensing, so there're none.

> And I still am not happy about not fingerprinting the downloads (bitbake uses fingerprints in all its recipes to ensure download integrity).

Well, bitbake is slow bloat ;-). This project was a practical hack which quite randomly picked up some attention (I wish my other projects which I really try do clean(er) picked as much attention).

**Comment by pfalcon** [comment]
@olaf-mandel : Ok, you closed this, any decision you made on this?

**Comment by olaf-mandel** [comment]
I noticed that my include file is far too small: the SDK `driver_lib` example makes use of more ROM functions that also need to be added to the file, e.g. `uart_div_modify()`.

Mostly, it is currently abandon-ware: sleeping on my hard drive for another day. If I get around to expanding the file, I would probably make it and its generating script available as a separate repo.

BTW: have you thought of an answer to my last question over at #119?

**Comment by pfalcon** [comment]
I see, just had a need to dump couple of function prototypes, resolved in an adhoc manner. Added comment to #119.

**Pull request closed without merging**
