### PR TITLE
Added SDK 1.5.0.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks, how this was tested?

**Comment by slaff** [comment]
> Thanks, how this was tested?
@pfalcon do you mean if tested the 1.5.0 SDK or the changes that I've made in the Makefile. If it is the latter I just ran ```make``` to see if the new SDK will be fetched.

**Comment by pfalcon** [comment]
Nope, that's easy part. Did you actually try to build some firmware with 1.5.0-based SDK, flash it, and make sure that it works as expected on device? I don't have access to esp8266 this month, so need to be cautious what to merge.

**Comment by slaff** [comment]
@pfalcon Good question. I will try to build Sming and/or Espruino (https://github.com/slaff/esp8266.dev.box#esp8266-dev)   and check if it works. I will let you know later today or tomorrow.

**Comment by pfalcon** [comment]
Thanks.

**Comment by pfalcon** [comment]
Also, feel free to try https://github.com/micropython/micropython (that's my usual testcase).

**Comment by slaff** [comment]
Sming library compiles, but the Basic_Blink has some issue with the linking:
```
/opt/Espressif/sdk//lib/libwpa.a(wpa_auth.o): In function `wpa_receive':
(.irom0.text+0x9a0): undefined reference to `aes_wrap'
/opt/Espressif/sdk//lib/libwpa.a(wpa_auth.o): In function `__wpa_send_eapol':
(.irom0.text+0xd73): undefined reference to `aes_wrap'
collect2: error: ld returned 1 exit status
make: *** [out/build/app.out] Error 1
```
I guess some ld files need to be updated. Or Espressif forgot to include the object code of `aes_wrap` 

The same story with micropython:
```
==> default: /opt/Espressif/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/lib/libwpa.a(wpa_auth.o): In function `wpa_receive':
==> default: (.irom0.text+0x9a0): undefined reference to `aes_wrap'
==> default: /opt/Espressif/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/lib/libwpa.a(wpa_auth.o): In function `__wpa_send_eapol':
==> default: (.irom0.text+0xd73): undefined reference to `aes_wrap'
==> default: make: *** [build/firmware.elf] Error 1

```

Any idea how to solve this?

**Comment by susisstrolch** [comment]
That's mentioned in Espressif Readme. You have to add libcrypto to the linker options...

Sent by mobile device

**Comment by eliabieri** [comment]
User application needs to add "-lcrypto" in LINKFLAGS_eagle.app.v6 of Makefile.

**Comment by pfalcon** [comment]
So, breaking backwards compatibility is not ok for esp-open-sdk. I've merged the patch, except 1.4.0 remains the default. Also leaving this ticket open to remind about the issue (I plan to look into it when time permits).

**Comment by pfalcon** [comment]
Ok, so the issues with switching to 1.5.0+ as the default is that it *requires* linking with libcrypto.a . That's because some objects which were previously in e.g. libwpa.a were moved to lincrypto.a (apparently, to not duplicate them in newly introduced libwpa2.a). My plan was to preserve backwards compatibility by copying "missing" objects back to libwpa.a - that should not lead to any forward compatibility either (well, unless similarly named objects in different libs contain different symbols, which is pretty crazy on its own). That's plan is now implemented in master.

However, note that libcrypto.a was introduced in 1.2.0, so just asking apps to be patched would be fair solution and still would be compatible with few latest SDK releases. Well, esp-open-sdk's aim was to stay backwards compatible as far as possible, so I still think solution with patching libwpa.a is right way.

But feedback is welcome. @dpgeorge: yours too.

**Comment by dpgeorge** [comment]
Personally I would not merge libcrypto objects into libwpa.  When you upgrate to a new SDK then it could be expected that some things break, and it's easy to fix by just adding -lcrypto.  That way people slowly adapt their applications to the evolving SDK, instead of the SDK getting more and more complex to remain backwards compatible.

**Comment by pfalcon** [comment]
> When you upgrate to a new SDK then it could be expected that some things break

Not in a well-maintained software component. At least not with a minor version upgrade. esp-open-sdk's aim always has been to provide common and unified interface to vendor SDK. This is in turn based on the idea that newer vendor SDK version doesn't mean better (indeed, some people (not me) think the opposite), so there should be freedom to build against any vendor SDK version (as long as it's possible, and munging libs isn't blocker for that).

Anyway, this seems to work reasonably well, and 1.5.0 is now default.

**Pull request closed without merging**
