### PR TITLE
Cleanup2

### PR DESCRIPTION
**Pull request by olaf-mandel**
This is a replacement for #117, with each change broken out into a separate commit.

The final state of this is not quite identical to #117: there are some small bug fixes and improvements here that are missing in #117.

### CODE REVIEW

**Comment by olaf-mandel** [comment]
I also added two merges: the first is to prevent the history of #117 from getting lost now that that branch is deleted and the second one is to sync with upstream master.

**Comment by olaf-mandel** [comment]
Had to add one more commit because somewhere along the line, I lost bootstrapping.

**Comment by pfalcon** [comment]
Sorry, but this change is out of date. Let's look at e.g. https://github.com/olaf-mandel/esp-open-sdk/commit/cbc09d9b2950a04168c5278ca9c520b8a952e372 . It's already merged as 88a0fd7ce6dbbf9bb6a5ea08472c6d57e0fef89b. Thus, this patch should not contain it. Please rebase your changes onto the latest master.

> I also added two merges:

If you looked at the project history, you've noticed that the project follows a clean linear history approach. And when you'll be doing a rebase mentioned above, you'll notice another reason why merges should be avoided: rebases by default don't work across merges.

**Comment by pfalcon** [comment]
Also, to clarify, the whole idea of having broken-down changes is not to merge them in one slurp still (why, original blob could have been merged like that). It's to review and decide them one by one, and decide which are good, which don't.

**Comment by olaf-mandel** [comment]
> Sorry, but this change is out of date. Let's look at e.g. olaf-mandel@cbc09d9 . It's already merged as 88a0fd7. Thus, this patch should not contain it. Please rebase your changes onto the latest master.
> [...]
> If you looked at the project history, you've noticed that the project follows a clean linear history approach. [...]

Ok, I discarded all the old history and rebased the branch (minus the two merges) onto master. I am more used to flows that contain lots of merges but this linear flow is fine, too (now that I know this is by design).

> Also, to clarify, the whole idea of having broken-down changes is not to merge them in one slurp still (why, original blob could have been merged like that). It's to review and decide them one by one, and decide which are good, which don't.

Now that each step is broken down, there is nothing preventing you from looking at each commit individually and deciding to ~~merge~~ use it in the linear history or not. Once you have found a commit you don't like, only go to the one before it and let me know what you found wanting.

I didn't make pull requests for each individual commit because that would take *forever* (TM): there is still 21 commits or 20 pull requests. Handing them in, waiting for acceptance and then handing in the next would be frustrating for both of us: I already have all of these commits, so why not show all of them to you? And you would not see the final result of the "cleanup" until nearly the end of the commit chain.

**Comment by pfalcon** [comment]
> I didn't make pull requests for each individual commit

Sure, there's no need for that - I'll be cherry-picking using native git, and for review, github easily allows to review individual commits of an aggregate PR.

**Comment by pfalcon** [comment]
> I don't think we finished deciding where to place the .PHONY list: end of public config as documentation or beginning of internal vars to mark as not changeable.

I don't consider .PHONY list on its own any public "documentation" (people aren't supposed to know what .PHONY is, and if the criteria for splitting is what people should tweak vs should not tweak, it should be in "should not" section).

**Comment by pfalcon** [comment]
Out of date.

**Pull request closed without merging**
