### PR TITLE
Added sdk 2.0.0.

### PR DESCRIPTION
**Pull request by jeremyd2019**
Per pfalcon/esp-open-sdk#183

### CODE REVIEW

**Comment by fvpalha** [comment]
Hi @jeremyd2019 

I changed the Makefile:
`VENDOR_SDK = 2.0.0`

After I tried build my code and this error occured:

```
/opt/esp-open-sdk/sdk/lib/libmain.a(spi_flash.o): In function `flash_gd25q32c_write_status':
(.text+0x6d0): undefined reference to `Enable_QMode'
/opt/esp-open-sdk/sdk/lib/libmain.a(spi_flash.o): In function `flash_gd25q32c_write_status':
(.text+0x6e1): undefined reference to `Enable_QMode'
collect2: error: ld returned 1 exit status
make: *** [build/rom0.elf] Error 1
Makefile:156: recipe for target 'build/rom0.elf' failed
```

**Comment by jeremyd2019** [comment]
@fvpalha : I did a little searching, and it looks like you are still using the old linker script (specifically `eagle.rom.addr.v6.ld`) with the new SDK.  The only difference in that file between 1.5.4 and 2.0.0 is the addition of the Enable_QMode symbol.

**Comment by fvpalha** [comment]
Hi @jeremyd2019 .

I am using the `eagle.rom.addr.v6.ld` file of ESP8266_NONOS_SDK_V2.0.0_16_07_19 folder. This file have the Enable_QMode defined.

I do not know what is wrong.

**Comment by pfalcon** [comment]
@jeremyd2019 : Thanks, merged. Note that the next commit is https://github.com/pfalcon/esp-open-sdk/commit/2abe5d08038c65da65d3fcd897ad18db95ceb1e2 , which adds default implementation of user_rf_cal_sector_set() to avoid breaking compatibility with existing projects - similarly how it was done with user_rf_pre_init() previously.

**Comment by flannelhead** [comment]
@pfalcon Is the actual implementation missing from that commit though? I just see the changes to the makefile.

**Comment by pfalcon** [comment]
D'oh! And rebased (git pull --rebase).

**Comment by jeremyd2019** [comment]
I ran into a minor issue building after your additional commit.  Pull request forthcoming

**Pull request merged**
